[project]
name = "math"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "claude-agent-sdk>=0.1.3",
    "httpx>=0.28.1",
    "mcp>=1.17.0",
    "nest-asyncio>=1.6.0",
    "networkx>=3.5",
    "pyyaml>=6.0.3",
    "urllib3>=2.5.0",
]
